//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lesson12.Views
{
    using System;
    using System.Collections.Generic;
    
    public partial class LeTranKhanhDuy_SACH
    {
        public string Ltkd_MaSach { get; set; }
        public string Ltkd_TenSach { get; set; }
        public Nullable<int> Ltkd_SoTrang { get; set; }
        public Nullable<int> Ltkd_NamXB { get; set; }
        public string Ltkd_MaTG { get; set; }
        public Nullable<bool> Ltkd_TrangThai { get; set; }
    }
}
