//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lesson12.Views
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class LeTranKhanhDuy_2210900020Entities : DbContext
    {
        public LeTranKhanhDuy_2210900020Entities()
            : base("name=LeTranKhanhDuy_2210900020Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<LeTranKhanhDuy_SACH> LeTranKhanhDuy_SACH { get; set; }
        public virtual DbSet<LeTranKhanhDuy_TACGIA> LeTranKhanhDuy_TACGIA { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
